### ISSUE TITLE
SyntaxError: 'with' statements are not valid in strict mode

### ISSUE THREAD

**Issue by pahmed** [Lightstreamer/Lightstreamer-example-StockList-client-reactnative#1]
Hi, I got syntax error when I try to run the demo `SyntaxError: 'with' statements are not valid in strict mode`

I'm using;
react-native-cli: 2.0.1
react-native: 0.41.2
npm: 4.0.5

**Comment by pahmed** [comment]
@dario-weswit any way to fix/workaround this?

**Comment by dEEpProjects** [comment]
Hi,
the **Lightstreamer Node.js Client Library**, used in this demo, is not yet strict mode compatible. In order to avoid such problem you need to ignore Lightstreamer npm module from the Babel transformation.

Make sure that your _.babelrc_ file includes:

`"ignore": ["node_modules/lightstreamer-client/lightstreamer.js"]`
or 
`"ignore": ["node_modules/lightstreamer-client/**/*.js"]`

**Comment by pahmed** [comment]
I tried the suggested solution but I'm getting another error
```
Unable to resolve module vertx from /Users/xyz/node_modules/lightstreamer-client/lightstreamer.js: Module does not exist in the module map or in these directories:
  /Users/xyz/node_modules
```

**Comment by dEEpProjects** [comment]
Hi,
as the _package.json_ file says, the right Lightstreamer-client npm module version for this demo is **_~6.2.7_**, so you must use that version (which has not dependencies with vertx module).

**Comment by pahmed** [comment]
It is working now, thank you :)
